Objetivo 7 v2
modejota/StoragIV pull request #33
Opened 2021-12-11 11:15 UTC by modejota

2021-12-11 11:38 UTC, modejota commented
@JJ Listo para revisión

2021-12-17 06:38 UTC, JJ requested changes
El milestone al que está asignado no incluye de ninguna forma explícita este desarrollo, ni aparentemente implícita. Es demasiado genérico, en todo caso.

2021-12-17 07:48 UTC, JJ reviewed
:+1: Buen trabajo, pero igual me habría gustado que lo elegido no se pareciera tanto a lo que ha elegido @slowmybrosh.

2021-12-17 07:48 UTC, JJ commented on .gitignore
> +.config/
Esto no es muy estándar

2021-12-17 07:48 UTC, JJ commented on docs/tools.md
> +Barajé también usar [typescript-loggin](https://www.npmjs.com/package/typescript-logging), pero al probarlo me pareció algo complicado, y, además, llevaba más de un año sin actualizarse, por lo que d
typo

2021-12-17 07:55 UTC, merged